### ISSUE TITLE
Received message from unsupported device with Zigbee model 'TS0202' and manufacturer name '_TZ3000_lf56vpxj'

### ISSUE THREAD

**Issue by droidblastnz** [Suxsem/Telink-Zigbee-serial-flash-tool#1]
So I am getting this error when using [https://pvvx.github.io/TS0202_TZ3000/](url)

Received message from unsupported device with Zigbee model 'TS0202' and manufacturer name '_TZ3000_lf56vpxj'

Couple of questions. 

- On the FT232RL USB TO TTL I assume I set to 3.3v not 5v with the jumper?
- On the FT232RLI use RTS to RST which is not one of the lower end pins a but on the side?
- I wire the TS0202 GND to FT232RLI GND
- I wire TS0202 Vbat-T to FT232RLI VCC which is 3.3v if the jmp is set to 3v

**Comment by Suxsem** [comment]
Hi, where do you see the errore? In zigbee2mqtt? It doesn't have anything to do with the flash tool....and the firmware you linked is not mine, you should ask in that repository (that said, i suggest to try to repair the devie again)

> On the FT232RL USB TO TTL I assume I set to 3.3v not 5v with the jumper?

Yes!!!

> On the FT232RLI use RTS to RST which is not one of the lower end pins a but on the side?

Yes, you have to use the one on the side

> I wire the TS0202 GND to FT232RLI GND

Yes

> I wire TS0202 Vbat-T to FT232RLI VCC which is 3.3v if the jmp is set to 3v

Yes
